### ISSUE TITLE
Dependency warning + compilation error

### ISSUE THREAD

**Issue by serversideapps** [chrisnappin/play-recaptcha-v2-example#1]
Hi there!

I like your project very much. I actually could make it work, but there is a dependency and a compilation issue I want you to know about.

First I get the dependency warning:

Found intransitive dependency (com.nappin:play-recaptcha_2.11:2.1) while publishMavenStyle is true, but Maven repositories do not support intransitive dependencies.

It seems that you are aware of the problem, because you added 'notTransitive()' to the dependency in build.sbt.

I had to use 'exclude("com.typesafe.play", "play")' instead of 'notTransitive()' to be able to remove this warning.

A more severe issue is with compilation:

\app\controllers\JavascriptForm.scala:93: value resolveRecaptchaErrors is not a member of com.nappin.play.recaptcha.WidgetHelper

I had to comment out this line to be able to compile. Nevertheless the captcha checking mechanism works, so your project is already useful for me.

**Comment by chrisnappin** [comment]
Hi and thanks for your interest! I'm part way through working on the next release, so the latest code in this repo depends upon the latest code in the play-recaptcha repo (v2.2 which doesn't exist yet!)

If you want working code to use the current latest build of play-recaptcha, please checkout the v2.1 tag of this project. I always tag the example code with the same version number as the play-recaptcha module the example uses.

Hope that helps!

**Comment by serversideapps** [comment]
Sorry, I found this project directly through Google search and did not look around, so I have not noticed that there is a stable version of this example and this one is only beta. I think this answers my question and you can close this issue.

Thanks again for your great work!

**Comment by chrisnappin** [comment]
No worries, I'll update the readme to point to the releases.
